# Site settings
title:          Gyroscoping
description:    "New York City: One Halal Cart at a time."
baseurl:        ""
url:            "https://chesterhow.github.io"

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
